// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from '/Users/yanghui/Desktop/未命名文件夹/vercle_test/node_modules/.pnpm/@ant-design+icons@4.8.0/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import ProfileOutlined from '/Users/yanghui/Desktop/未命名文件夹/vercle_test/node_modules/.pnpm/@ant-design+icons@4.8.0/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import UserOutlined from '/Users/yanghui/Desktop/未命名文件夹/vercle_test/node_modules/.pnpm/@ant-design+icons@4.8.0/node_modules/@ant-design/icons/es/icons/UserOutlined';
import BorderBottomOutlined from '/Users/yanghui/Desktop/未命名文件夹/vercle_test/node_modules/.pnpm/@ant-design+icons@4.8.0/node_modules/@ant-design/icons/es/icons/BorderBottomOutlined';
import ArrowLeftOutlined from '/Users/yanghui/Desktop/未命名文件夹/vercle_test/node_modules/.pnpm/@ant-design+icons@4.8.0/node_modules/@ant-design/icons/es/icons/ArrowLeftOutlined';
export default { HomeOutlined, ProfileOutlined, UserOutlined, BorderBottomOutlined, ArrowLeftOutlined };
