// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/yanghui/Desktop/未命名文件夹/vercle_test/src/pages/user/model';
import model_2 from '/Users/yanghui/Desktop/未命名文件夹/vercle_test/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'user.model', model: model_1 },
model_2: { namespace: '@@initialState', model: model_2 },
} as const
